/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class unicorn_Unicorn_NewHook */

#ifndef _Included_unicorn_Unicorn_NewHook
#define _Included_unicorn_Unicorn_NewHook
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
